use std::collections::{BTreeMap, BTreeSet};
use std::env;
use std::fs;
use std::path::PathBuf;

use syn::{Fields, Item, ItemEnum};

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=src/components/mod.rs");
    println!("cargo:rerun-if-changed=../../assets/extracted/data_component.json");

    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let components_path = manifest_dir.join("src/components/mod.rs");
    let registry_path = manifest_dir.join("../../assets/extracted/data_component.json");

    let components_source =
        fs::read_to_string(&components_path).expect("failed to read components/mod.rs");
    let registry_source =
        fs::read_to_string(&registry_path).expect("failed to read data_component.json");

    let registry: BTreeMap<String, i32> =
        serde_json::from_str(&registry_source).expect("failed to parse data_component.json");
    let item_component = parse_item_component_enum(&components_source);
    let variants = collect_component_variants(&item_component, &registry);

    verify_registry_coverage(&variants, &registry);
    write_generated_ids(&variants);
}

struct ComponentVariant {
    ident: String,
    key: String,
    id: i32,
    fields: Fields,
}

fn parse_item_component_enum(source: &str) -> ItemEnum {
    let file = syn::parse_file(source).expect("failed to parse components/mod.rs");
    file.items
        .into_iter()
        .find_map(|item| match item {
            Item::Enum(item_enum) if item_enum.ident == "ItemComponent" => Some(item_enum),
            _ => None,
        })
        .expect("could not find ItemComponent enum")
}

fn collect_component_variants(
    item_component: &ItemEnum,
    registry: &BTreeMap<String, i32>,
) -> Vec<ComponentVariant> {
    let mut seen_keys = BTreeSet::new();
    let mut seen_ids = BTreeSet::new();

    item_component
        .variants
        .iter()
        .map(|variant| {
            let ident = variant.ident.to_string();
            let key = registry_key(&ident);
            let id = *registry.get(&key).unwrap_or_else(|| {
                panic!("ItemComponent::{ident} maps to missing registry key {key}")
            });

            if !seen_keys.insert(key.clone()) {
                panic!("duplicate data component registry key {key}");
            }

            if !seen_ids.insert(id) {
                panic!("duplicate data component protocol id {id} for {key}");
            }

            ComponentVariant {
                ident,
                key,
                id,
                fields: variant.fields.clone(),
            }
        })
        .collect()
}

fn verify_registry_coverage(variants: &[ComponentVariant], registry: &BTreeMap<String, i32>) {
    let implemented = variants
        .iter()
        .map(|variant| variant.key.as_str())
        .collect::<BTreeSet<_>>();

    for key in registry.keys() {
        if !implemented.contains(key.as_str()) {
            panic!("data component registry key {key} has no ItemComponent variant");
        }
    }
}

fn write_generated_ids(variants: &[ComponentVariant]) {
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let generated_path = out_dir.join("item_component_ids.rs");

    let mut by_id = variants.iter().collect::<Vec<_>>();
    by_id.sort_by_key(|variant| variant.id);

    let mut out = String::new();
    out.push_str("// Autogenerated by build.rs. Do not edit manually.\n\n");
    out.push_str("#[derive(Clone, Copy, Debug, PartialEq, Eq)]\n");
    out.push_str("pub enum ItemComponentKind {\n");
    for variant in variants {
        out.push_str("    ");
        out.push_str(&variant.ident);
        out.push_str(",\n");
    }
    out.push_str("}\n\n");

    out.push_str("impl ItemComponentKind {\n");
    out.push_str("    pub fn from_protocol_id(id: i32) -> Option<Self> {\n");
    out.push_str("        match id {\n");
    for variant in &by_id {
        out.push_str("            ");
        out.push_str(&variant.id.to_string());
        out.push_str(" => Some(Self::");
        out.push_str(&variant.ident);
        out.push_str("),\n");
    }
    out.push_str("            _ => None,\n");
    out.push_str("        }\n");
    out.push_str("    }\n\n");
    out.push_str("    pub fn protocol_id(self) -> i32 {\n");
    out.push_str("        match self {\n");
    for variant in variants {
        out.push_str("            Self::");
        out.push_str(&variant.ident);
        out.push_str(" => ");
        out.push_str(&variant.id.to_string());
        out.push_str(",\n");
    }
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    out.push_str("impl ItemComponent {\n");
    out.push_str("    pub fn kind(&self) -> ItemComponentKind {\n");
    out.push_str("        match self {\n");
    for variant in variants {
        out.push_str("            Self::");
        out.push_str(&variant.ident);
        out.push_str(pattern_for_fields(&variant.fields));
        out.push_str(" => ItemComponentKind::");
        out.push_str(&variant.ident);
        out.push_str(",\n");
    }
    out.push_str("        }\n");
    out.push_str("    }\n\n");
    out.push_str("    pub fn protocol_id(&self) -> i32 {\n");
    out.push_str("        self.kind().protocol_id()\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    out.push_str("#[cfg(test)]\n");
    out.push_str("mod generated_item_component_id_tests {\n");
    out.push_str("    use super::ItemComponentKind;\n\n");
    out.push_str("    #[test]\n");
    out.push_str("    fn generated_ids_match_data_component_registry() {\n");
    for variant in &by_id {
        out.push_str("        assert_eq!(ItemComponentKind::");
        out.push_str(&variant.ident);
        out.push_str(".protocol_id(), ");
        out.push_str(&variant.id.to_string());
        out.push_str(", ");
        out.push_str(&format!("{:?}", variant.key));
        out.push_str(");\n");
    }
    out.push_str("    }\n");
    out.push_str("}\n");

    fs::write(generated_path, out).expect("failed to write item_component_ids.rs");
}

fn pattern_for_fields(fields: &Fields) -> &'static str {
    match fields {
        Fields::Named(_) => " { .. }",
        Fields::Unnamed(_) => "(..)",
        Fields::Unit => "",
    }
}

fn registry_key(variant: &str) -> String {
    let path = match variant {
        "VillagerVariant" => "villager/variant",
        "WolfVariant" => "wolf/variant",
        "WolfSoundVariant" => "wolf/sound_variant",
        "WolfCollar" => "wolf/collar",
        "FoxVariant" => "fox/variant",
        "SalmonSize" => "salmon/size",
        "ParrotVariant" => "parrot/variant",
        "TropicalFishPattern" => "tropical_fish/pattern",
        "TropicalFishBaseColor" => "tropical_fish/base_color",
        "TropicalFishPatternColor" => "tropical_fish/pattern_color",
        "MooshroomVariant" => "mooshroom/variant",
        "RabbitVariant" => "rabbit/variant",
        "PigVariant" => "pig/variant",
        "PigSoundVariant" => "pig/sound_variant",
        "CowVariant" => "cow/variant",
        "CowSoundVariant" => "cow/sound_variant",
        "ChickenVariant" => "chicken/variant",
        "ChickenSoundVariant" => "chicken/sound_variant",
        "ZombieNautilusVariant" => "zombie_nautilus/variant",
        "FrogVariant" => "frog/variant",
        "HorseVariant" => "horse/variant",
        "PaintingVariant" => "painting/variant",
        "LlamaVariant" => "llama/variant",
        "AxolotlVariant" => "axolotl/variant",
        "CatVariant" => "cat/variant",
        "CatSoundVariant" => "cat/sound_variant",
        "CatCollar" => "cat/collar",
        "SheepColor" => "sheep/color",
        "ShulkerColor" => "shulker/color",
        other => return format!("minecraft:{}", to_snake_case(other)),
    };

    format!("minecraft:{path}")
}

fn to_snake_case(value: &str) -> String {
    let mut out = String::with_capacity(value.len() + 8);
    let mut previous_was_lowercase = false;

    for ch in value.chars() {
        if ch.is_uppercase() {
            if previous_was_lowercase {
                out.push('_');
            }
            out.push(ch.to_ascii_lowercase());
            previous_was_lowercase = false;
        } else {
            out.push(ch);
            previous_was_lowercase = ch.is_ascii_alphanumeric();
        }
    }

    out
}
