name: "Feature Request"
description: Suggest a feature or idea for this server.
labels: enhancement
body:
  - type: markdown
    attributes:
      value: This should only be used for new ideas / features. For general questions, please use our [Discord Server](https://discord.gg/6QPZgUy4sA) instead.

  - type: textarea
    attributes:
      label: Description of the feature
      description: "Please provide a clear and concise description of the feature you are requesting. Include any relevant details or use cases that can help us understand the value and purpose of this feature."
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: I have confirmed that...
      options:
        - label: ... such a feature does not exist already.
          required: false
        - label: ... I ticked all the boxes without reading them
          required: false
        - label: ... such a feature request has not been submitted already.
          required: false
    
